# fly.toml app configuration file generated for tuist-crm on 2024-08-09T11:07:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tuist-crm"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile"

[env]
  ENABLE_DB_MIGRATIONS=false
  NODE_OPTIONS="--max-old-space-size=4096"

[deploy]
  release_command = "./release.sh"

[processes]
app = "node dist/src/main"
worker = "yarn worker:prod"

[[vm]]
  size = "performance-1x"
  memory = "4gb"

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.http_options]
      [services.ports.http_options.response]
        [services.ports.http_options.response.headers]
          Referrer-Policy = "strict-origin-when-cross-origin"
          Strict-Transport-Security = "max-age=63072000; includeSubDomains"
          X-Content-Type-Options = "nosniff"
          X-Frame-Options = "SAMEORIGIN"
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
